require('./food-test');
require('./speed-boost-test');
require('./virus-test');
require('./game-packager-test');
require('./food-generator-test');
require('./player-properties-test');
require('./player-movements-test');
require('./player-eats-food-test');
require('./players-eat-each-other-test')
